//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Eventbooking
    {
        [ScaffoldColumn(false)]
        public int BookingId { get; set; }
        [Required]
        public string BookingDate { get; set; }
        [Required]
        public int RegId { get; set; }
        [Required]
        public string EventDate { get; set; }
        [Required]
        public string EventName { get; set; }
        public string Lobby { get; set; }
        public string Hall { get; set; }
        public string Room { get; set; }
        public string Dining { get; set; }
        public string Parking { get; set; }
        public string Status { get; set; }
        [ForeignKey("RegId")]
        public virtual Registration Registration { get; set; }
    }
}
