//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_ProjectEntity : DbContext
    {
        public MVC_ProjectEntity()
            : base("name=MVC_ProjectEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Eventbooking> Eventbookings { get; set; }
        public virtual DbSet<HallService> HallServices { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<TblAdmin> TblAdmins { get; set; }
    }
}
